project:
  type: website
  output-dir: docs

website:
  title: "buenoas"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - publications.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

