project:
  type: website
  output-dir: docs

website:
  title: "buenoas"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: publications.qmd
        text: Publicações
      - href: apps.qmd
        text: Aplicativos
      - href: posts.qmd
        text: ifR

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

