project:
  type: website
  output-dir: docs

title: "Anderson Bueno"
about:
  template: jolla
  image: foto_perfil_crop.jpg
  links:
    - icon: twitter
      text: X
      href: https://twitter.com/buenoas
    - icon: github
      text: GitHub
      href: https://github.com/buenoas
    - icon: researchgate
      text: ResearchGate
      href: https://www.researchgate.net/profile/Anderson-Bueno
    - icon: googlescholar
      text: Google Scholar
      href: https://scholar.google.com/citations?user=inyeGdgAAAAJ&hl=en&oi=ao

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
