---
title: "Publicações"
---

## 2024

-   Luypaert T, **Bueno AS**, Haugaasen T, Peres CA (2024) Extending Species‐Area Relationships Into the Realm of Ecoacoustics: The Soundscape‐Area Relationship. *Ecology Letters* 27(10):e14529. <https://doi.org/10.1111/ele.14529>

-   Guimaraes AF, Querido LCA, Rocha T, Rodrigues DJ, Viana PL, Bergallo HG, Fernandes GW, Toma TSP, Streit H, Overbeck GE, Souza AQS, Lima AP, Rosa CA, Grelle CEV, Lopes AM, Curcino A, Paula AS, Andriolo A, Dias A, Santos AT, Bernardes AA, Oliveira ABS, Barros AAM, Lins e Silva ACB, Cruz ACR, Holanda ASS, **Bueno AS**, Nunes-Freitas AF, Yves A, Alencar AS, Scabin AB, Manzzato AG, Lima ACS, Pontes ARM, Castro AB, Gomes AM, Santos AB, Rosado BHP, Batista CAS, Siqueira CC, Fontana CS, Rocha CFD, Brocado CR, Doria CRC, Castilho CV, Silva CP, Cordeiro C, Cronemberger CAMM, Andretti CB, Cornelius C, Campos C, Borges-Matos C, Keller C, Cavalcante CO, Dambros CS, Machado DNSM, Tassinari D, Rosa DCP, Villela DM, Chiarani E, Geisler EF, Velez-Martin E, Carvalho EARJ, Dreschsler-Santos ER, Lourenço EC, Franklin E, Higashikawa EM, Pezzini F, Roque FO, Baccaro FB, Becker FG, Cabeceira FG, Florencio FP, Barbosa FR, Zuquim G, Braga GB, Vargas GK, Mourao G, Rousseau GX, Lima HC, Farias HLS, Kaefer IL, Ghizoni IR, Noronha JC, Oliveira JL, Santos RSJ, Jarenkow JA, Melo-Junior JCF, Santos JVC, Oliveira J, Souza JLP, Baungratz JFA, Morais JW, Silva JM, Silva JG, Wingert JM, Menger J, Ferre J, Dyrell JS, Silva-Goncalves KC, Torralvo K, Cruz KS, Sylvestre LS, Ribas LA, Battirola LD, Ramos L, Caires LR, Carvalho LCS, Stegmann LF, Carvalho LN, Menezes LS, Costa LM, Podgaiski LR, Silveira LF, Malabarba LR, Frangipani MA, Tabarelli M, Nascimento MT, Marques MCM, Spies MR, Santos MAO, Anaicy M, Vital MJS, Silveira M, Vieira MV, Araujo MAM, Silveira MAPA, Barros MF, Faitanin MA, Iguatemy M, Cunha MS, Murakami MMS, Messias MR, Martins MB, Camana M, Correa NM, Fonseca NC, Benavides OOP, Rodrigues PJF, Andrade PL, Pequeno PACL, Gananca PHS, Ferreira PPS, Andrade PCR, Azarak PA, Fraga R, Rabelo RM, Santos RLS, Barbosa RI, Dala-Corte RB, Vicente RE, Perdiz RO, Araujo RPC, Andrade RTG, Portela RCQ, Fadini R, Feitosa RM, Santa-Brigida R, Cerqueira R, Muller SC, Santorelli S, Santos SB, Cechin SZ, Avilla SS, Pansini S, Aragon S, Figueiredo TS, Sobroza TV, Guimaraes TFR, Emilio T, Amorim TA, Izzo TJ, Sobral T, Santos TG, Vincent TL, Rocha TL, Pillar VD, Mesquita VP, Silva VD, Cyrino VME, Borges-Junior VNT, Layme VMG, Mota WG, Souza WN, Drose W, Silva WR, Magnusson WE (2024) Disentangling the veil line for Brazilian biodiversity: An overview from two long-term research programs reveals huge gaps in ecological data reporting. *Science of the Total Environment* 950:174880. <https://doi.org/10.1016/j.scitotenv.2024.174880>

-   Palmeirim AP, Benchimol M, Storck-Tonon D, **Bueno AS**, Jones IL, Klein G, Peres CA (2024) Biodiversity responses to insular fragmentation in Amazonia: Two decades of research in the Balbina Hydroelectric Reservoir. *Zoological Research: Diversity and Conservation* 1(2):106--116. <https://doi.org/10.24272/j.issn.2097-3772.2023.007>

## 2023

-   Carvalho RL, Resende AF, Barlow J, França FM, Moura MR, Maciel R, Alves-Martins F, Shutt J, Nunes CA, Elias F, Silveira JM, Stegmann L, Baccaro FB, Juen L, Schietti J, Aragão L, Berenguer E, Castello L, Costa FRC, Guedes ML, Leal CG, Lees AC, Isaac V, Nascimento RO, Phillips OL, Schmidt FA, ter Steege H, Vaz-de-Mello F, Venticinque EM, Vieira ICG, Zuanon J, Ferreira J, Carvalho RL, Resende AF, Barlow J, França F, Moura MR, Maciel R, Alves-Martins F, Shutt J, Nunes CA, Elias F, Silveira JM, Stegmann L, Baccaro FB, Juen L, Schietti J, Aragão L, Berenguer E, Castello L, Costa FRC, Guedes ML, Leal CG, Lees AC, Isaac V, Nascimento RO, Phillips OL, Schmidt FA, ter Steege H, Vaz-de-Mello F, Venticinque EM, Vieira ICG, Zuanon J, Ferreira J, Geber Filho AN dos S, Ruschel A, Calor AR, de Lima Alves A, Muelbert AE, Quaresma A, Vicentini A, Piedade AR da, Oliveira AA de, Aleixo A, Casadei-Ferreira A, Gontijo A, Hercos A, Andriolo A, Lopes A, Pontes-Lopes A, Santos APM dos, Oliveira AB da S de, Mortati AF, Salcedo AKM, Albernaz AL, Fares AL, Andrade AL, Oliveira Pes AM, Faria APJ, Batista APB, Puker A, **Bueno AS**, Junqueira AB, Holanda de Andrade ALR, Ghidini AR, Galuch AV, Menezes ASO de, Manzatto AG, Correa ASAS, Queiroz ACM, Zanzini AC da S, Olivo Neto AM, Melo AWF de, Guimaraes AF, Castro AB, Borges A, Ferreira AB, Marimon BS, Marimon-Junior BH, Flores BM, de Resende BO, Albuquerque BW, Villa B, Davis B, Nelson B, Williamson B, Melo BSB de, Cintra BBL, Santos BB, Prudente B da S, Luize BG, Godoy BS, Rutt CL, Duarte Ritter C, Silva CVJ, Ribas CR, Peres CA, Azevêdo CAS de, Freitas C, Cordeiro CL, Brocardo CR, Castilho C, Levis C, Doria CR da C, Arantes CC, Santos CA dos, Jakovac CC, Silva CA, Benetti CJ, Lasmar C, Marsh CJ, Andretti CB, Oliveira CP de, Cornelius C, Alves da Rosa C, Baider C, Gualberto CG, Deus CP de, Monteiro Jr. C da S, Santos Neto CR dos, Lobato CMC, Santos CRM dos, Penagos CCM, Costa D da S, Vieira DLM, Aguiar DPP de, Veras DS, Pauletto D, Braga D de L, Storck-Tonon D, Almeida D da F, Douglas D, Amaral DD do, Gris D, Luther D, Edwards DP, Guimarães DP, Santos DC dos, Campana DR de S, Nogueira DS, Silva DR da, Dutra DB de S, Rosa DCP, Silva DAS da, Pedroza D, Anjos DV, Melo Lima DV, Silvério DV, Rodrigues D de J, Bastos D, Daly D, Barbosa EM, Arenas ERC, Oliveira EA de, Santos EA dos, Santana ECC de, Guilherme E, Vidal E, Campos-Filho EM, van den Berg E, Morato EF, da Silva ER, Marques EE, Pringle EG, Nichols E, Andresen E, Farias E de S, Siqueira ELS de, de Albuquerque EZ, Görgens EB, Cunha EJR da, Householder E, Novo EMM de L, Oliveira FF de, Roque F de O, Coletti F, Reis F, Moreira FFF, Todeschini F, Carvalho FA, Coelho de Souza F, Silva FAB, Carvalho FG, Cabeceira FG, d'Horta FM, Mendonça FP, Florêncio FP, Carvalho FR de, Arruda FV de, Nonato FA da S, Santana FD, Durgante F, Souza FKS de, Obermuller FA, Castro FS de, Wittmann F, Sales FM da S, Neto FV-, Salles FF, Borba GC, Damasco G, Barros GG, Brejão GL, Jardim GA, Prance GT, Lima GR, Desidério GR, Melo G da C de, Carmo GHP do, Cabral GS, Rousseau GX, da Silva GC, Schwartz G, Griffiths H, Queiroz HL de, Espírito-Santo HMV, Cabette HSR, Nascimento HEM, Vasconcelos HL, Medeiros H, Aguiar HJAC de, Leão H, Wilker I, Gonçalves IC, de Sousa Gorayeb I, Miranda IP de A, Brown IF, Santos ICS, Fernandes IO, Fernandes I, Delabie JHC, de Abreu JC, Gama Neto J de L, Costa JBP, Noronha JC, de Brito JG, Wolfe J, Santos JC, Ferreira-Ferreira J, e Gomes JO, Lasky JR, de Faria Falcão JC, Costa JG, Cravo JS, Guerrero JEB, Muñoz Gutiérrez JA, Carreiras J, Lanna J, Silva Brito J, Schöngart J, Mendes Aguiar JJ, Lima J, Barroso JG, Noriega JA, Pereira JL da S, Nessimian JL, Souza JLP de, de Toledo JJ, Magalhães JLL, Camargo JL, Oliveira JMB, Ribeiro JMF, Silva JO de A, da Silva Guimarães JR, Hawes JE, Andrade-Silva J, Revilla JDC, da Silva JS, da Silva Menger J, Rechetelo J, Stropp J, Barbosa JF, do Vale JD, Louzada J, Cerqueira Silva JC, da Silva KD, Melgaço K, Carvalho KS, Yamamoto KC, Mendes KR, Vulinec K, Maia LF, Cavalheiro L, Vedovato LB, Demarchi LO, Giacomin L, Dumas LL, Maracahipes L, Brasil LS, Ferreira LV, Calvão LB, Maracahipes-Santos L, Reis LP, da Silva LF, de Oliveira Melo L, Carvalho LC da S, Casatti L, Amado LL, de Matos LS, Vieira L, Prado LP do, Alencar L, Fontenele L, Mazzei L, Navarro Paolucci L, Zanzini LP, Carvalho LN, Crema LC, Brulinger LFB, Montag LF de A, Naka LN, Azara L, Silveira LF, Nunes LG de O, Rosalino LM do C, Mestre LAM, Bonates LC de M, Coelho L de S, Borges LHM, Lourenço L da S, Freitas MAB, Brito MT da S, Pombo MM, da Rocha M, Cardoso MR, Guedes MC, Raseira MB, Medeiros MB de, Carim M de JV, Simon MF, Pansonato MP, dos Anjos MR, Nascimento MT, Souza MR de, Monteiro MGT, da Silva MJ, Uehara-Prado M, Oliveira MA de, Callisto M, Vital MJS, o Santos MPD, Silveira M, Oliveira MVND, Pérez-Mayorga MA, Carniello MA, Lopes MA, Silveira MAP de A, Esposito MC, Maldaner ME, Passos MIS, Anacléto MJP, Costa MKS, Martins MP, Piedade MTF, Irume MV, Costa MMS da, Maximiano MF de A, Freitas MG, Cochrane MA, Gastauer M, Almeida MRN, Souza MF de, Catarino M, Costa Batista M, Massam MR, Martins MF de O, Holmgren M, Almeida M, Dias MS, Espírito Santo NB, Benone NL, Ivanauskas NM, Medeiros N, Targhetta N, Félix NS, Ferreira N, Hamada N, Campos N, Giehl NF da S, Metcalf OC, Silva OGM da, Cerqueira PV, Moser P, Miranda PN, Peruquetti PSF, Alverga PP de P, Prist P, Souto P, Brando P, Pompeu P dos S, Barni PE, Graça PM de A, Morandi PS, Cruz PV, da Silva PG, Bispo PC, Camargo PB de, Sarmento PS de M, Souza P, Andrade RB de, Braga RB, Boldrini R, Bastos RC, Assis RL de, Salomão RP, Leitão RP, Mendes RNG, Carpanedo R de S, Melinski RD, Ligeiro R, e Pérez REP, Barbosa RI, Cajaiba RL, Silvano RAM, Salomão RP, Hilário RR, Martins RT, Perdiz R de O, Vicente RE, Silva RJ da, Koroiva R, Solar R, Silva R da C, s de Lima RB, Silva R dos SA da, Mariano R, Ribeiro RAB, Fadini RF, Oliveira RLC de, Feitosa RM, Matavelli R, Mormul RP, da Silva RR, Zanetti R, Barthem R, Almeida RPS, Ribeiro SC, r Costa Neto SV da, Nienow S, Oliveira SAV de, Borges SH, Milheiras S, Ribeiro SP, Couceiro SRM, Sousa SA de, Rodrigues SB, Dutra SL, Mahood S, Vieira SA, Arrolho S, Silva SS da, Triana SP, Laurance S, Kunz SH, Alvarado ST, Rodrigues THA, Santos TF dos, Machado TL da S, Feldpausch TR, Sousa T, Michelan TS, Emilio T, Brito T de F, André T, Barbosa TAP, Miguel TB, Izzo TJ, Laranjeiras TO, Mendes TP, Silva TSF, Krolow TK, Begot TO, Baker TR, Domingues TF, Giarrizzo T, Bentos TV, Haugaasen T, Peixoto U, Pozzobom UM, Korasaki V, Ribeiro VS, Scudeller VV, Oliveira VHF, Landeiro VL, Santos Ferreira VR, Silva V de NG, Gomes VHF, Oliveira VC de, Firmino V, Santiago WTV, Beiroz W, Almeida WR de, Oliveira WL de, Silva WC da, Castro W, Dáttilo W, Cruz WJA da, Silva WFM da, Magnusson WE, Laurance W, Milliken W, Paula WS de, Malhi Y, Shimabukuro YE, Lima YG de, Shimano Y, Feitosa Y (2023) Pervasive gaps in Amazonian ecological research. *Current Biology* 33(16):3495-3504.e4. <https://doi.org/10.1016/j.cub.2023.06.077>

-   Cardoso I, **Bueno AS**, Morante-Filho JC (2023) Number of forest fragments and understory plants exert opposite effects on multiple facets of bird diversity in eucalypt plantations. *Landscape Ecology* 38(4):1069--1083. <https://doi.org/10.1007/s10980-023-01601-5>

## 2022

-   Müller GA, de Mello CF, **Bueno AS**, de Alcantara Azevedo WT, Alencar J (2022) Little noticed, but very important: The role of breeding sites formed by bamboos in maintaining the diversity of mosquitoes (Diptera: Culicidae) in the Atlantic Forest biome. *PLOS ONE* 17(9):e0273774. <https://doi.org/10.1371/journal.pone.0273774>

-   Palmeirim AF, Emer C, Benchimol M, Storck-Tonon D, **Bueno AS**, Peres CA (2022) Emergent properties of species-habitat networks in an insular forest landscape. *Science Advances* 8(34):eabm0397. <https://doi.org/10.1126/sciadv.abm0397>

-   Luypaert T, **Bueno AS**, Masseli GS, Kaefer IL, Campos‐Cerqueira M, Peres CA, Haugaasen T (2022) A framework for quantifying soundscape diversity using Hill numbers. *Methods in Ecology and Evolution* 13(10):2262--2274. <https://doi.org/10.1111/2041-210x.13924>

-   Braga PLM, Borges SH, Peres CA, Loiselle BA, Blake JG, Menger J, **Bueno AS**, Anciães M, Teófilo FH, Maximiano MFA, Souza AHN, Boss RL, Baccaro FB (2022) Connecting Amazonian historical biogeography and local assemblages of understorey birds: Recurrent guild proportionality within areas of endemism. *Journal of Biogeography* 49(2):324--338. <https://doi.org/10.1111/jbi.14301>

-   Almeida-Maués PCR, **Bueno AS**, Palmeirim AF, Peres CA, Mendes-Oliveira AC (2022) Assessing assemblage-wide mammal responses to different types of habitat modification in Amazonian forests. *Scientific Reports* 12(1):1797. <https://doi.org/10.1038/s41598-022-05450-1>

## 2021

-   Henriques LMP, Dantas S, Santos LB, **Bueno AS**, Peres CA (2021) Avian extinctions induced by the oldest Amazonian hydropower mega dam: evidence from museum collections and sighting data spanning 172 years. *PeerJ* 9:e11979. <https://doi.org/10.7717/peerj.11979>

-   Jones IL, **Bueno AS**, Benchimol M, Palmeirim AF, Storck-Tonon D, Peres CA (2021) Using Relict Species--Area Relationships to Estimate the Conservation Value of Reservoir Islands to Improve Environmental Impact Assessments of Dams. In: Matthews TJ, Triantis KA, Whittaker RJ (eds.) *The Species--Area Relationship: Theory and Application*. Pages 417-437. Ecology, Biodiversity and Conservation. Cambridge University Press. <https://doi.org/10.1017/9781108569422.023>

## 2020

-   **Bueno AS**, Peres CA (2020) The role of baseline suitability in assessing the impacts of land-use change on biodiversity. *Biological Conservation* 243:108396. <https://doi.org/10.1016/j.biocon.2019.108396>

-   **Bueno AS**, Masseli GS, Kaefer IL, Peres CA (2020) Sampling design may obscure species--area relationships in landscape‐scale field studies. *Ecography* 43(1):107--118. <https://doi.org/10.1111/ecog.04568>

## 2019

-   **Bueno AS**, Peres CA (2019) Patch‐scale biodiversity retention in fragmented landscapes: Reconciling the habitat amount hypothesis with the island biogeography theory. *Journal of Biogeography* 46(3):621--632. <https://doi.org/10.1111/jbi.13499>

-   Bonanomi J, Tortato FR, Gomes R de SR, Penha JM, **Bueno AS**, Peres CA (2019) Protecting forests at the expense of native grasslands: Land-use policy encourages open-habitat loss in the Brazilian cerrado biome. *Perspectives in Ecology and Conservation* 17(1):26--31. <https://doi.org/10.1016/j.pecon.2018.12.002>

## 2018

-   **Bueno AS**, Dantas SM, Henriques LMP, Peres CA (2018) Ecological traits modulate bird species responses to forest fragmentation in an Amazonian anthropogenic archipelago. *Diversity and Distributions* 24(3):387--402. <https://doi.org/10.1111/ddi.12689>

## 2016

-   Graça MB, Morais JW, Franklin E, Pequeno PACL, Souza JLP, **Bueno AS** (2016) Combining Taxonomic and Functional Approaches to Unravel the Spatial Distribution of an Amazonian Butterfly Community. *Environmental Entomology* 45(2):301--309. <https://doi.org/10.1093/ee/nvv183>

## 2012

-   **Bueno AS**, Bruno RS, Pimentel TP, Sanaiotti TM, Magnusson WE (2012) The width of riparian habitats for understory birds in an Amazonian forest. *Ecological Applications* 22(2):722--734. <https://doi.org/10.1890/11-0789.1>

## 2010

-   Wallau GL, Della-Flora F, **Bueno AS**, Corso J, Ortiz MF, Cáceres NC (2010) Behaviour of the Common Moorhen in Rio Grande do Sul, Brazil. *acta ethologica* 13(2):127--135. <https://doi.org/10.1007/s10211-010-0082-5>
